DROP TABLE IF EXISTS COMMUNITY_REQ CASCADE;

DROP TABLE IF EXISTS COMMUNITY_STS CASCADE;

DROP TABLE IF EXISTS COUNTRY CASCADE;

DROP TABLE IF EXISTS EDUCATION CASCADE;

DROP TABLE IF EXISTS GENDER CASCADE;

DROP TABLE IF EXISTS INTEREST CASCADE;

DROP TABLE IF EXISTS THERAPIST CASCADE;

DROP TABLE IF EXISTS THRPST_CNTRY CASCADE;

DROP SEQUENCE IF EXISTS COMMUNITY_REQ_SEQUENCE;

DROP SEQUENCE IF EXISTS COMMUNITY_STS_SEQUENCE;

DROP SEQUENCE IF EXISTS COUNTRY_SEQUENCE;

DROP SEQUENCE IF EXISTS EDUCATION_SEQUENCE;

DROP SEQUENCE IF EXISTS GENDER_SEQUENCE;

DROP SEQUENCE IF EXISTS INTEREST_SEQUENCE;

DROP SEQUENCE IF EXISTS THERAPIST_SEQUENCE;

CREATE SEQUENCE COMMUNITY_REQ_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE COMMUNITY_STS_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE COUNTRY_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE EDUCATION_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GENDER_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE INTEREST_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE THERAPIST_SEQUENCE START WITH 1 INCREMENT BY 1;


CREATE TABLE COMMUNITY_REQ
(
    COMMUNITY_REQ_ID INTEGER NOT NULL,
    COMMUNITY_STS_ID INTEGER,
    REVIEW_DATE      TIMESTAMP(6),
    REJECTED_REASON  VARCHAR(255),
    PRIMARY KEY (COMMUNITY_REQ_ID)
);

CREATE TABLE COMMUNITY_STS
(
    COMMUNITY_STS_ID INTEGER NOT NULL,
    COMM_STATUS_NAME VARCHAR(255),
    PRIMARY KEY (COMMUNITY_STS_ID)
);

CREATE TABLE COUNTRY
(
    COUNTRY_ID INTEGER       NOT NULL,
    ISO2       VARCHAR(255) NOT NULL UNIQUE,
    ISO3       VARCHAR(255),
    NAME_LOW   VARCHAR(255) NOT NULL UNIQUE,
    NAME_UP    VARCHAR(255) NOT NULL UNIQUE,
    NUM_CODE   INTEGER,
    PHONE_CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY (COUNTRY_ID)
);

CREATE TABLE EDUCATION
(
    GRADUATION_YEAR  INTEGER      NOT NULL,
    COUNTRY_ID       INTEGER      NOT NULL,
    EDUCATION_ID     INTEGER      NOT NULL,
    THERAPIST_ID     INTEGER      NOT NULL,
    CERTIFICATE_PATH VARCHAR(255) NOT NULL,
    INSTITUTION      VARCHAR(255) NOT NULL,
    PRIMARY KEY (EDUCATION_ID)
);

CREATE TABLE GENDER
(
    GENDER_ID   INTEGER       NOT NULL,
    GENDER_NAME VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (GENDER_ID)
);

CREATE TABLE INTEREST
(
    IS_COURSE                  BOOLEAN NOT NULL,
    IS_SOCIAL_MEDIA_PROMOTIONS BOOLEAN NOT NULL,
    IS_STUDY_GROUPS            BOOLEAN NOT NULL,
    IS_SUPERVISIONS            BOOLEAN NOT NULL,
    INTEREST_ID                INTEGER NOT NULL,
    PRIMARY KEY (INTEREST_ID)
);

CREATE TABLE THERAPIST
(
    DATE_OF_BIRTH       DATE         NOT NULL,
    IS_ADJST_RATE       BOOLEAN,
    IS_MIGRATION_EXP    BOOLEAN,
    RATE                INTEGER      NOT NULL,
    YEARS_OF_EXPERIENCE INTEGER      NOT NULL,
    COMMUNITY_REQ_ID    INTEGER UNIQUE,
    COUNTRY_ID          INTEGER,
    GENDER_ID           INTEGER,
    INTEREST_ID         INTEGER UNIQUE,
    REGISTRATION_DATE   TIMESTAMP(6),
    THERAPIST_ID        INTEGER       NOT NULL,
    EMAIL               VARCHAR(255) NOT NULL UNIQUE,
    EXPERIENCE_DESC     VARCHAR(255),
    FIRST_NAME          VARCHAR(255) NOT NULL,
    LAST_NAME           VARCHAR(255) NOT NULL,
    MIDDLE_NAME         VARCHAR(255),
    MOTIVATION_DESC     VARCHAR(255),
    SEC_LAST_NAME       VARCHAR(255),
    PRIMARY KEY (THERAPIST_ID)
);


CREATE INDEX IDX_COMMUNITY_REQ_01
    ON COMMUNITY_REQ (COMMUNITY_STS_ID);

CREATE INDEX IDX_COUNTRY_01
    ON COUNTRY (ISO2);

CREATE INDEX IDX_COUNTRY_02
    ON COUNTRY (PHONE_CODE);

CREATE INDEX IDX_GENDER_01
    ON GENDER (GENDER_NAME);

CREATE INDEX IDX_THERAPIST_01
    ON THERAPIST (EMAIL);

ALTER TABLE IF EXISTS COMMUNITY_REQ
    ADD CONSTRAINT FK_COMMUNITY_REQ_01
        FOREIGN KEY (COMMUNITY_STS_ID)
            REFERENCES COMMUNITY_STS;

ALTER TABLE IF EXISTS EDUCATION
    ADD CONSTRAINT FK_EDUCATION_01
        FOREIGN KEY (COUNTRY_ID)
            REFERENCES COUNTRY;

ALTER TABLE IF EXISTS EDUCATION
    ADD CONSTRAINT FK_EDUCATION_02
        FOREIGN KEY (THERAPIST_ID)
            REFERENCES COUNTRY;

ALTER TABLE IF EXISTS THERAPIST
    ADD CONSTRAINT FK_THERAPIST_01
        FOREIGN KEY (COMMUNITY_REQ_ID)
            REFERENCES COMMUNITY_REQ;

ALTER TABLE IF EXISTS THERAPIST
    ADD CONSTRAINT FK_THERAPIST_02
        FOREIGN KEY (GENDER_ID)
            REFERENCES GENDER;

ALTER TABLE IF EXISTS THERAPIST
    ADD CONSTRAINT FK_THERAPIST_03
        FOREIGN KEY (INTEREST_ID)
            REFERENCES INTEREST;

ALTER TABLE IF EXISTS THERAPIST
    ADD CONSTRAINT FK_THERAPIST_04
        FOREIGN KEY (COUNTRY_ID)
            REFERENCES COUNTRY;
